# Generated by Django 3.1.5 on 2021-06-27 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('store_email_id', models.EmailField(max_length=30)),
                ('mobile_number', models.IntegerField()),
                ('address_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(max_length=100)),
                ('store_licence', models.CharField(max_length=30)),
                ('store_registration_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_type_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='StoreType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=60)),
                ('medicine_details', models.CharField(max_length=100)),
                ('medicine_price', models.IntegerField()),
                ('medicine_quantity', models.IntegerField()),
                ('medicine_expiry_date', models.DateTimeField()),
                ('medicine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.medicinetype')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.medicalstore')),
            ],
        ),
        migrations.AddField(
            model_name='medicalstore',
            name='store_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.storetype'),
        ),
    ]
