# Generated by Django 3.1.5 on 2021-06-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedetails',
            name='medicine_expiry_date',
            field=models.DateField(),
        ),
    ]
