# Generated by Django 3.1.5 on 2021-06-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210628_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedetails',
            name='medicine_expiry_date',
            field=models.DateTimeField(),
        ),
    ]
