# Generated by Django 3.1.5 on 2021-07-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210628_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinetype',
            name='description',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
