# Generated by Django 3.1.5 on 2021-07-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_medicinetype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalstore',
            name='mobile_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
